/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/actors/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Actors
         * @description 全量同步：返回所有演员（供 Android 拉取）
         */
        get: operations["sync_actors_actors_sync_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Actors
         * @description 获取演员列表（返回所有有消息的演员）
         */
        get: operations["get_actors_actors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors/{actor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Actor Detail
         * @description 获取演员详情
         */
        get: operations["get_actor_detail_actors__actor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Messages
         * @description 获取消息列表（游标分页）
         */
        get: operations["get_messages_messages_get"];
        put?: never;
        /**
         * Create Message
         * @description 创建新消息
         */
        post: operations["create_message_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Message Dates
         * @description 获取指定月份中有消息的日期及数量
         */
        get: operations["get_message_dates_messages_dates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Messages
         * @description 全量同步：返回所有消息的完整详情（含 media 元数据和 tag）
         */
        get: operations["sync_messages_messages_sync_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/with-detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Messages With Detail
         * @description 获取消息列表，含完整媒体详情（游标分页）
         */
        get: operations["get_messages_with_detail_messages_with_detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Message Detail
         * @description 获取单条消息详情
         */
        get: operations["get_message_detail_messages__message_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Message
         * @description 删除消息
         */
        delete: operations["delete_message_messages__message_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Message
         * @description 更新消息：文字、actor、媒体顺序
         */
        patch: operations["update_message_messages__message_id__patch"];
        trace?: never;
    };
    "/messages/create-from-client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Message From Client
         * @description 客户端主导创建消息：接受客户端提供的 ID，幂等
         */
        post: operations["create_message_from_client_messages_create_from_client_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Messages
         * @description 合并多条消息：文本拼接、媒体合并到第一条消息，删除其余消息。
         */
        post: operations["merge_messages_messages_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/around/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Messages Around
         * @description 以指定消息为中心，向前/向后加载消息
         */
        get: operations["get_messages_around_messages_around__message_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Media
         * @description 获取媒体列表（游标分页，显示所有媒体）
         */
        get: operations["get_media_media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Media Feed
         * @description 按 MessageMedia 展开的媒体流（Telegram风格，媒体可重复），支持 tag/actor 筛选
         */
        get: operations["get_media_feed_media_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Media Detail
         * @description 获取媒体详情
         */
        get: operations["get_media_detail_media__media_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}/starred": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Toggle Media Starred
         * @description 切换媒体收藏状态
         */
        put: operations["toggle_media_starred_media__media_id__starred_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Media Rating
         * @description 更新媒体评分
         */
        put: operations["update_media_rating_media__media_id__rating_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Increment View Count
         * @description 增加媒体查看次数
         */
        put: operations["increment_view_count_media__media_id__view_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/around/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Media Around
         * @description 以指定媒体为中心，向前/向后加载媒体
         */
        get: operations["get_media_around_media_around__media_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出路径下的文件和文件夹
         * @description 列出指定路径下的所有文件和文件夹信息
         *
         *     参数:
         *     - path: 要列出的路径，默认为当前目录
         *
         *     返回:
         *     - path: 当前路径
         *     - items: 文件和文件夹列表，每个项目包含名称、路径、类型、大小和修改时间
         */
        get: operations["list_path_files_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除文件或文件夹
         * @description 删除指定的文件或文件夹
         *
         *     参数:
         *     - path: 要删除的文件或文件夹路径
         *
         *     返回:
         *     - message: 操作结果消息
         */
        delete: operations["delete_path_files_delete_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 移动文件或文件夹
         * @description 移动文件或文件夹到新位置
         *
         *     参数:
         *     - source_path: 源文件或文件夹路径
         *     - destination_path: 目标文件或文件夹路径
         *
         *     返回:
         *     - message: 操作结果消息
         */
        post: operations["move_path_files_move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 重命名文件或文件夹
         * @description 重命名文件或文件夹
         *
         *     参数:
         *     - path: 要重命名的文件或文件夹路径
         *     - new_name: 新的名称
         *
         *     返回:
         *     - message: 操作结果消息
         */
        put: operations["rename_path_files_rename_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 创建文件或文件夹
         * @description 创建新的文件或文件夹
         *
         *     参数:
         *     - path: 要创建的文件或文件夹路径
         *     - type: 类型，必须是 'file' 或 'directory'
         *
         *     返回:
         *     - message: 操作结果消息
         */
        post: operations["create_path_files_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传文件
         * @description 上传文件到指定路径
         *
         *     参数:
         *     - file: 要上传的文件
         *     - path: 上传目标路径，默认为当前目录
         *
         *     返回:
         *     - message: 操作结果消息
         *     - path: 上传后的文件路径
         */
        post: operations["upload_file_files_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/upload-media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传媒体文件
         * @description 上传媒体文件（图片/视频），自动存入按日期组织的目录。
         *     返回的 file_path 可直接用于 POST /messages 的 files 字段。
         */
        post: operations["upload_media_files_upload_media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tags
         * @description 获取所有标签，支持按名称搜索，附带每个标签的消息数量。
         */
        get: operations["get_tags_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sync Changes
         * @description 增量拉取变更日志。since 为空或超过保留期返回 410，客户端应回退到全量同步。
         *
         *     游标格式升级为 (timestamp, id) 复合游标，避免同一 timestamp 多行时跳页：
         *     过滤条件等价于 (timestamp > since_dt) OR (timestamp = since_dt AND id > since_id)。
         */
        get: operations["get_sync_changes_sync_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply Sync Changes
         * @description 接收 Android 客户端推送的变更，按序应用。Last-write-wins by updated_at。
         *
         *     整个批次在单一事务中执行：全部成功才 commit，任意失败则全量 rollback。
         */
        post: operations["apply_sync_changes_api_sync_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Events
         * @description SSE 端点：推送变更通知。客户端收到后调用 /sync/changes 拉取实际数据。
         */
        get: operations["sync_events_sync_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description 获取数据库统计信息：各表记录数、存储统计、最近活动。
         */
        get: operations["get_stats_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/sync-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sync Logs
         * @description 游标分页浏览 sync_log 表。
         */
        get: operations["get_sync_logs_admin_sync_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActorDetailResponse */
        ActorDetailResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Avatar Path */
            avatar_path?: string | null;
            /**
             * Avatar Url
             * @default
             */
            avatar_url: string;
            /** Message Count */
            message_count: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
        };
        /** ActorResponse */
        ActorResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Avatar Path */
            avatar_path?: string | null;
            /**
             * Avatar Url
             * @default
             */
            avatar_url: string;
            /** Message Count */
            message_count: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** ActorSyncResponse */
        ActorSyncResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Avatar */
            avatar?: string | null;
        };
        /** Body_upload_file_files_upload_post */
        Body_upload_file_files_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
            /**
             * Path
             * @default .
             */
            path: string;
        };
        /** Body_upload_media_files_upload_media_post */
        Body_upload_media_files_upload_media_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** ClientMediaFile */
        ClientMediaFile: {
            /** Id */
            id: number;
            /** File Path */
            file_path: string;
        };
        /** CursorResponse */
        CursorResponse: {
            /** Items */
            items: components["schemas"]["MessageResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Has More */
            has_more: boolean;
        };
        /** FileInfo */
        FileInfo: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Type */
            type: string;
            /** Size */
            size: number | null;
            /** Mtime */
            mtime: number;
        };
        /** FileListResponse */
        FileListResponse: {
            /** Path */
            path: string;
            /** Items */
            items: components["schemas"]["FileInfo"][];
        };
        /** FileOperationResponse */
        FileOperationResponse: {
            /** Message */
            message: string;
        };
        /** FileUploadResponse */
        FileUploadResponse: {
            /** Message */
            message: string;
            /** Path */
            path: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MediaCursorResponse */
        MediaCursorResponse: {
            /** Items */
            items: components["schemas"]["MediaResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Prev Cursor */
            prev_cursor?: string | null;
            /** Has More */
            has_more: boolean;
            /**
             * Has More Before
             * @default false
             */
            has_more_before: boolean;
        };
        /** MediaDetailResponse */
        MediaDetailResponse: {
            /** Id */
            id: number;
            /** File Path */
            file_path: string;
            /**
             * File Url
             * @default
             */
            file_url: string;
            /** File Size */
            file_size: number | null;
            /** Mime Type */
            mime_type: string | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Rating */
            rating: number;
            /**
             * Starred
             * @default false
             */
            starred: boolean;
            /** View Count */
            view_count: number;
            /**
             * Thumb Url
             * @default
             */
            thumb_url: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
        };
        /** MediaResponse */
        MediaResponse: {
            /** Id */
            id: number;
            /** File Path */
            file_path: string;
            /**
             * File Url
             * @default
             */
            file_url: string;
            /** File Size */
            file_size: number | null;
            /** Mime Type */
            mime_type: string | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Rating */
            rating: number;
            /**
             * Starred
             * @default false
             */
            starred: boolean;
            /** View Count */
            view_count: number;
            /**
             * Thumb Url
             * @default
             */
            thumb_url: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** MessageCreate */
        MessageCreate: {
            /** Text */
            text?: string | null;
            /** Actor Id */
            actor_id?: number | null;
            /**
             * Files
             * @default []
             */
            files: string[];
            /**
             * Tag Ids
             * @default []
             */
            tag_ids: number[];
        };
        /** MessageCreateFromClient */
        MessageCreateFromClient: {
            /** Id */
            id: number;
            /** Text */
            text?: string | null;
            /** Actor Id */
            actor_id?: number | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Files
             * @default []
             */
            files: components["schemas"]["ClientMediaFile"][];
        };
        /** MessageDateCount */
        MessageDateCount: {
            /** Date */
            date: string;
            /** Count */
            count: number;
        };
        /** MessageDatesResponse */
        MessageDatesResponse: {
            /** Dates */
            dates: components["schemas"]["MessageDateCount"][];
        };
        /** MessageDetailCursorResponse */
        MessageDetailCursorResponse: {
            /** Items */
            items: components["schemas"]["MessageDetailResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Prev Cursor */
            prev_cursor?: string | null;
            /** Has More */
            has_more: boolean;
            /**
             * Has More Before
             * @default false
             */
            has_more_before: boolean;
        };
        /** MessageDetailResponse */
        MessageDetailResponse: {
            /** Id */
            id: number;
            /** Text */
            text?: string | null;
            /** Actor Id */
            actor_id?: number | null;
            /** Actor Name */
            actor_name?: string | null;
            /** Media Count */
            media_count: number;
            /**
             * Starred
             * @default false
             */
            starred: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Media Items */
            media_items: components["schemas"]["MessageMediaItem"][];
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["MessageTagItem"][];
        };
        /** MessageMediaItem */
        MessageMediaItem: {
            /** Id */
            id: number;
            /** File Path */
            file_path: string;
            /**
             * File Url
             * @default
             */
            file_url: string;
            /** Mime Type */
            mime_type: string | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Thumb Url
             * @default
             */
            thumb_url: string;
            /**
             * Starred
             * @default false
             */
            starred: boolean;
        };
        /** MessageMerge */
        MessageMerge: {
            /** Message Ids */
            message_ids: number[];
        };
        /** MessageResponse */
        MessageResponse: {
            /** Id */
            id: number;
            /** Text */
            text?: string | null;
            /** Actor Id */
            actor_id?: number | null;
            /** Actor Name */
            actor_name?: string | null;
            /** Media Count */
            media_count: number;
            /**
             * Starred
             * @default false
             */
            starred: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** MessageSyncMediaItem */
        MessageSyncMediaItem: {
            /** Id */
            id: number;
            /**
             * File Url
             * @default
             */
            file_url: string;
            /** File Path */
            file_path: string;
            /**
             * File Hash
             * @default
             */
            file_hash: string;
            /** File Size */
            file_size: number | null;
            /** Mime Type */
            mime_type: string | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /**
             * Rating
             * @default 0
             */
            rating: number;
            /**
             * Starred
             * @default false
             */
            starred: boolean;
            /**
             * Thumb Url
             * @default
             */
            thumb_url: string;
            /**
             * Position
             * @default 0
             */
            position: number;
        };
        /** MessageSyncResponse */
        MessageSyncResponse: {
            /** Id */
            id: number;
            /** Text */
            text?: string | null;
            /** Actor Id */
            actor_id?: number | null;
            /** Actor Name */
            actor_name?: string | null;
            /**
             * Starred
             * @default false
             */
            starred: boolean;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Media Items */
            media_items: components["schemas"]["MessageSyncMediaItem"][];
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["MessageTagItem"][];
        };
        /** MessageTagItem */
        MessageTagItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
        };
        /** MessageUpdate */
        MessageUpdate: {
            /** Text */
            text?: string | null;
            /** Actor Id */
            actor_id?: number | null;
            /** Starred */
            starred?: boolean | null;
            /** Created At */
            created_at?: string | null;
            /** Media Order */
            media_order?: number[] | null;
        };
        /** SyncApplyItem */
        SyncApplyItem: {
            /** Entitytype */
            entityType: string;
            /** Operation */
            operation: string;
            /** Entityid */
            entityId: number;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /** SyncApplyRequest */
        SyncApplyRequest: {
            /** Changes */
            changes: components["schemas"]["SyncApplyItem"][];
        };
        /** SyncApplyResponse */
        SyncApplyResponse: {
            /**
             * Applied
             * @default 0
             */
            applied: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /** Message */
            message?: string | null;
        };
        /** SyncChangeItem */
        SyncChangeItem: {
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: number;
            /** Operation */
            operation: string;
            /** Timestamp */
            timestamp: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            } | null;
        };
        /** SyncChangesResponse */
        SyncChangesResponse: {
            /** Changes */
            changes: components["schemas"]["SyncChangeItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Next Cursor Id */
            next_cursor_id?: number | null;
            /** Has More */
            has_more: boolean;
            /** Server Time */
            server_time: string;
        };
        /** TagResponse */
        TagResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Category */
            category?: string | null;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sync_actors_actors_sync_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorSyncResponse"][];
                };
            };
        };
    };
    get_actors_actors_get: {
        parameters: {
            query?: {
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_actor_detail_actors__actor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_messages_get: {
        parameters: {
            query?: {
                /** @description 游标，ISO 格式的 created_at */
                cursor?: string | null;
                limit?: number;
                actor_id?: number | null;
                starred?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_message_dates_messages_dates_get: {
        parameters: {
            query: {
                year: number;
                month: number;
                actor_id?: number | null;
                query_text?: string | null;
                media_id?: number | null;
                tag_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_messages_messages_sync_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSyncResponse"][];
                };
            };
        };
    };
    get_messages_with_detail_messages_with_detail_get: {
        parameters: {
            query?: {
                /** @description 游标，ISO 格式的 created_at */
                cursor?: string | null;
                /** @description 分页方向: 'forward' 加载更新的消息（cursor 之后） */
                direction?: string | null;
                limit?: number;
                actor_id?: number | null;
                /** @description 搜索文本，匹配 message.text */
                query_text?: string | null;
                /** @description 媒体 ID，查询包含该媒体的所有消息 */
                media_id?: number | null;
                /** @description 标签 ID，查询包含该标签的所有消息 */
                tag_id?: number | null;
                /** @description 是否收藏 */
                starred?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDetailCursorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_message_detail_messages__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_message_messages__message_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_message_messages__message_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_from_client_messages_create_from_client_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreateFromClient"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_messages_messages_merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageMerge"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_around_messages_around__message_id__get: {
        parameters: {
            query?: {
                limit?: number;
                actor_id?: number | null;
                query_text?: string | null;
                media_id?: number | null;
                tag_id?: number | null;
                starred?: boolean | null;
            };
            header?: never;
            path: {
                message_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDetailCursorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_media_get: {
        parameters: {
            query?: {
                /** @description 游标，格式为'created_at|position' */
                cursor?: string | null;
                /** @description 分页方向: 'forward' 加载更新的媒体 */
                direction?: string | null;
                limit?: number;
                message_id?: number | null;
                starred?: boolean | null;
                /** @description 媒体类型: 'video' 或 'image' */
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaCursorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_feed_media_feed_get: {
        parameters: {
            query?: {
                /** @description 游标：message_media.id */
                cursor?: number | null;
                limit?: number;
                tag_id?: number | null;
                actor_id?: number | null;
                starred?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaCursorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_detail_media__media_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_media_starred_media__media_id__starred_put: {
        parameters: {
            query: {
                starred: boolean;
            };
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_media_rating_media__media_id__rating_put: {
        parameters: {
            query: {
                rating: number;
            };
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    increment_view_count_media__media_id__view_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_around_media_around__media_id__get: {
        parameters: {
            query?: {
                limit?: number;
                starred?: boolean | null;
            };
            header?: never;
            path: {
                media_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaCursorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_path_files_list_get: {
        parameters: {
            query?: {
                path?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_path_files_delete_delete: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_path_files_move_post: {
        parameters: {
            query: {
                source_path: string;
                destination_path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_path_files_rename_put: {
        parameters: {
            query: {
                path: string;
                new_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_path_files_create_post: {
        parameters: {
            query: {
                path: string;
                type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOperationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_files_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_files_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_media_files_upload_media_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_media_files_upload_media_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tags_tags_get: {
        parameters: {
            query?: {
                /** @description 按名称模糊搜索 */
                name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sync_changes_sync_changes_get: {
        parameters: {
            query?: {
                /** @description ISO timestamp 游标，为空则返回 410 要求全量同步 */
                since?: string | null;
                /** @description 复合游标：上次最后一条 SyncLog.id，与 since 配合使用 */
                since_id?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncChangesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_sync_changes_api_sync_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncApplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_events_sync_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_stats_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_sync_logs_admin_sync_logs_get: {
        parameters: {
            query?: {
                /** @description 分页游标 (ISO datetime) */
                cursor?: string | null;
                limit?: number;
                /** @description 按实体类型筛选 */
                entity_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
