"""add transaction tables

Revision ID: 865aca0da8ff
Revises: f2a3b4c5d6e7
Create Date: 2026-06-11 17:33:23.304279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865aca0da8ff'
down_revision: Union[str, Sequence[str], None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('biz_no', sa.String(length=64), nullable=False),
    sa.Column('txn_time', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('counterparty', sa.String(length=256), nullable=True),
    sa.Column('product', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('raw_type', sa.String(length=64), nullable=True),
    sa.Column('raw_origin', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('excluded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'biz_no', name='uq_txn_source_bizno')
    )
    op.create_index(op.f('ix_transaction_category'), 'transaction', ['category'], unique=False)
    op.create_index(op.f('ix_transaction_direction'), 'transaction', ['direction'], unique=False)
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_source'), 'transaction', ['source'], unique=False)
    op.create_index(op.f('ix_transaction_txn_time'), 'transaction', ['txn_time'], unique=False)
    op.create_index('ix_txn_time_dir', 'transaction', ['txn_time', 'direction'], unique=False)
    op.create_table('txn_category_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword', name='uq_txn_rule_keyword')
    )
    op.create_index(op.f('ix_txn_category_rule_id'), 'txn_category_rule', ['id'], unique=False)
    op.create_index(op.f('ix_txn_category_rule_keyword'), 'txn_category_rule', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_txn_category_rule_keyword'), table_name='txn_category_rule')
    op.drop_index(op.f('ix_txn_category_rule_id'), table_name='txn_category_rule')
    op.drop_table('txn_category_rule')
    op.drop_index('ix_txn_time_dir', table_name='transaction')
    op.drop_index(op.f('ix_transaction_txn_time'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_source'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_direction'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_category'), table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
